apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/benwold-lgtm/MY-K8S-LAB
    targetRevision: HEAD
    path: ai-stack/charts/ai-agent
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true