apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-nfs-pv
spec:
  capacity:
    storage: 10Gi # WebUI only needs a few GBs for its SQLite DB
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # Keep empty to ensure it matches the PVC exactly
  nfs:
    path: /NFS_K8S_PV/open-webui # I recommend a sub-folder to keep it clean
    server: 192.168.1.250
  claimRef:
    namespace: ai-stack
    name: open-webui  