apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-models-pv
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /NFS_K8S_PV
    server: 192.168.1.250