apiVersion: v1
kind: Service
metadata:
  name: vllm-server
  namespace: ai-stack
spec:
  type: NodePort
  selector:
    app: vllm
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000