apiVersion: v1
kind: Service
metadata:
  name: comfyui
  namespace: comfyui
spec:
  type: {{ .Values.service.type }}
  selector:
    app: comfyui
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
