apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      nodeSelector:
        kubernetes.io/hostname: bengpu1
      containers:
        - name: vllm-container
          image: "vllm/vllm-openai:gemma4"
          #we use this command to run the pip fix and the server in one squence.
          command: ["/bin/sh", "-c"] 
          args:
            - |
              # Force install the required version despite the vLLM conflict
              pip install --no-cache-dir "transformers==5.5.0" "huggingface-hub>=1.9.1" --force-reinstall
              
              # Start the server using the python module directly
              python3 -m vllm.entrypoints.openai.api_server \
              --model google/gemma-4-26b-a4b-it \
              --quantization awq \
              --download-dir /data \
              --gpu-memory-utilization 0.90 \
              --max-model-len 4096 \
              --trust-remote-code
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-secret
                  key: token
            - name: VLLM_ENABLE_CUDA_COMPATIBILITY
              value: "0"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: model-data
              mountPath: /data
            - name: shm 
              mountPath: /dev/shm
          resources:
            limits:
              cpu: "8"
              memory: "32Gi"  
              nvidia.com/gpu: 1
            requests:
              cpu: "4"
              memory: "16Gi"
              nvidia.com/gpu: 1
      volumes:
        - name: model-data
          hostPath:
            path: /mnt/nvme/ai-stack/vllm/models  # This should match the path in your PVC file
            type: DirectoryOrCreate
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi