apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      nodeSelector:
        kubernetes.io/hostname: bengpu1
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "sku"
          operator: "Equal"
          value: "gpu"
          effect: "NoSchedule"
      containers:
        - name: vllm-container
          image: "vllm/vllm-openai:latest"
          #we use this command to run the pip fix and the server in one squence.
          command: ["/bin/sh", "-c"] 
          args:
            - |
              set -e
              #echo "--- STAGE 1: FORCING TRANSFORMERS UPDATE ---"
              echo "--- LAUNCHING MISTRAL_NEMO FP8 ---"
              python3 -m vllm.entrypoints.openai.api_server \
                --model mistralai/Mistral-Nemo-Instruct-FP8-2407 \
                --tokenizer-mode mistral \
                --download-dir /data \
                --gpu-memory-utilization 0.85 \
                --max-model-len 8192 \
                --enforce-eager \
                --trust-remote-code
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-secret
                  key: token
            - name: VLLM_MOE_TOPK
              value: "8"
            - name: PYTORCH_ALLOC_CONF
              value: "expandable_segments:True"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: model-data
              mountPath: /data
            - name: shm 
              mountPath: /dev/shm
          resources:
            limits:
              cpu: "8"
              memory: "32Gi"  
              nvidia.com/gpu: 1
            requests:
              cpu: "4"
              memory: "16Gi"
              nvidia.com/gpu: 1
      volumes:
        - name: model-data
          persistentVolumeClaim:
            claimName: vllm-models-pvc # Matches the name in step 1
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi