apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-pipelines-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"
  nfs:
    server: 192.168.1.250
    path: /NFS_K8S_PV/open-webui-pipelines
  claimRef:
    namespace: ai-stack
    name: open-webui-pipelines