apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd   # Management Location
spec:
  project: default
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia
    chart: gpu-operator
    targetRevision: v24.9.0
    helm:
      values: |
        driver:
          enable: true
          image:
            imageFullName: "nvcr.io/nvidia/driver:550.54.14-ubuntu22.04"
                   
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator # Installation Location
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
