apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd   # Management Location
spec:
  project: default
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia
    chart: gpu-operator
    targetRevision: v24.9.0
    helm:
      values: |
        driver:
          enable: true
          repository: nvcr.io/nvidia/
          version: "550.54.15"  # A broadly compatible stable version
          image: "driver"
          # # This tells the operator: [repository]/[image]:[version]-[OS]
          # If it still appends ubuntu24.04 and fails, we will use the 'FullImageName' trick.
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator # Installation Location
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
