image:
  repository: ghcr.io/ai-dock/comfyui
  tag: latest
  pullPolicy: Always

replicaCount: 1
revisionHistoryLimit: 3

service:
  type: NodePort
  port: 1111
  nodePort: 30084

nodeSelector:
  kubernetes.io/hostname: bengpu1

resources:
  requests:
    memory: "4Gi"
    cpu: "1000m"
    nvidia.com/gpu: 1
  limits:
    memory: "16Gi"
    cpu: "4000m"
    nvidia.com/gpu: 1

persistence:
  pvcName: comfyui-models-pvc
  storageClassName: nfs-client
  size: 50Gi
  mountPath: /root/.comfyui/models

environment:
  COMFYUI_FLAGS: "--listen 0.0.0.0"
  CF_QUICK_TUNNELS: "false"
