apiVersion: apps/v1
kind: Deployment  # Changed from Pod to Deployment for easier scaling
metadata:
  name: gpu-workload-pool
  namespace: default
spec:
  replicas: 2     # This will put one pod on each worker!
  selector:
    matchLabels:
      app: gpu-test
  template:
    metadata:
      labels:
        app: gpu-test
    spec:
      containers:
      - name: cuda-container
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "while true; do sleep 30; done"]
        resources:
          limits:
            nvidia.com/gpu: 1
