apiVersion: v1
kind: Pod
metadata:
  name: nvidia-gpu-test
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-worker1 
  containers:
  - name: cuda-container
    image: ubuntu:latest
    # We use 'sleep' because a raw Ubuntu image exits immediately otherwise
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    resources:
      limits:
        nvidia.com/gpu: 1
