apiVersion: v1
kind: Pod
metadata:
  name: nvidia-gpu-test
  namespace: default
spec:
  # This tells Kubernetes NOT to run on the master node
  nodeSelector:
    kubernetes.io/hostname: k8s-worker1 
  containers:
  - name: cuda-container
    image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-amd64
    resources:
      limits:
        nvidia.com/gpu: 1 # The scheduler looks for this!
        