replicaCount: 1
revisionHistoryLimit: 3

image:
  repository: vllm/vllm-openai
  tag: latest
  pullPolicy: Always

model:
  name: "Lorbus/Qwen3.6-27B-int4-AutoRound"
  downloadDir: "/data"

server:
  maxModelLen: 68000
  gpuMemoryUtilization: "0.97"
  maxNumSeqs: 1
  maxNumBatchedTokens: 2048

resources:
  limits:
    cpu: "8"
    memory: "32Gi"
    nvidia.com/gpu: 1
  requests:
    cpu: "4"
    memory: "16Gi"
    nvidia.com/gpu: 1

nodeSelector:
  kubernetes.io/hostname: bengpu1

gpuNodeSelector:
  node-role.kubernetes.io/gpunode: "true"

service:
  type: NodePort
  port: 8000
  nodePort: 30000

persistence:
  pvcName: vllm-models-nfs-pvc

shm:
  sizeLimit: 16Gi

env:
  extra:
    - name: VLLM_WORKER_MULTIPROC_METHOD
      value: "spawn"
    - name: NCCL_P2P_DISABLE
      value: "1"
    - name: VLLM_USE_FLASHINFER_SAMPLER
      value: "1"
    - name: VLLM_ALLOW_LONG_MAX_MODEL_LEN
      value: "1"
    - name: VLLM_MARLIN_USE_ATOMIC_ADD
      value: "1"
    - name: PYTORCH_CUDA_ALLOC_CONF
      value: "expandable_segments:True,max_split_size_mb:512"
    - name: CUDA_DEVICE_MAX_CONNECTIONS
      value: "8"
